# Mac でいう Cmd の位置に alt key をアサインしている。
# ctrl キーは小指の位置。

keymap:
  - name: Emacs
    application:
      not: wezterm
    remap:
      C-b: { with_mark: left }
      C-f: { with_mark: right }
      C-p: { with_mark: up }
      C-n: { with_mark: down }

      C-a: { with_mark: home }
      C-e: { with_mark: end }

      C-h: { with_mark: backspace }

      C-m: enter
      C-j: enter

      C-d: [delete, { set_mark: false }]

      C-k: [Shift-end, C-x, { set_mark: false }]
      C-leftbrace: esc


  # Chrome tab switching
  - name: Chrome
    application:
      only: Google-chrome
    remap:
      Shift-Alt-rightbrace: C-tab
      Shift-Alt-leftbrace: Shift-C-tab
      Alt-leftbrace: Alt-Left
      M-BTN_LEFT: C-BTN_LEFT

  # remap alt-key to control
  - name: Cmd key mapping
    remap:
      Alt-a: C-a
      Alt-b: C-b
      Alt-c: C-c
      Alt-d: C-d
      Alt-e: C-e
      Alt-f: C-f
      Alt-g: C-g
      Alt-h: C-h
      Alt-i: C-i
      Alt-j: C-j
      Alt-k: C-k
      Alt-l: C-l
      Alt-m: C-m
      Alt-n: C-n
      Alt-o: C-o
      Alt-p: C-p
      Alt-q: C-q
      Alt-r: C-r
      Alt-s: C-s
      Alt-t: C-t
      Alt-u: C-u
      Alt-v: C-v
      Alt-w: C-w
      Alt-x: C-x
      Alt-y: C-y
      Alt-z: C-z

  # find the app name by `wmctrl -x -l` on X
