# https://yiskw713.hatenablog.com/entry/2022/05/20/203540

[general]
import = [
  "~/.local/share/alacritty/themes/themes/zenburn.toml"
]


[window]
padding = { x= 8, y= 4}
option_as_alt = "Both"

[scrolling]
history = 100000
multiplier = 3

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 14.0
offset = { x = 0, y = 2 }


